services:
  # FastAPI app service
  fastapi_backend:
    build: .
    container_name: fastapi_backend
    image: fastapi_backend
    restart: always
    ports:
      - "${DOCKER_PORT:-8001}:8001"
    environment:
      - TZ=Asia/Dhaka
    volumes:
      - ${LOG_DIR}:/app/${LOG_DIR}
      - ./:/app
    networks:
      - custom-network
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --worker 4 --timeout-keep-alive 60

networks:
  custom-network:
    driver: bridge
